# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171014_0017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poststarred',
            table='posts_starred',
        ),
    ]
